name: iobroker npx install Windows 64bit Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: install
      run: |
        npm link
        cd ..
        mkdir iobroker-inst
        cd iobroker-inst
        npx iobroker

    - name: test
      run: curl --insecure http://127.0.0.1:8081 2> /dev/null | grep '<title>Admin</title>' &> /dev/null || exit 1